name: DeePTB tests.

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/devcontainer.yml'
      
jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.s1.outputs.test }}
      output2: ${{ steps.s2.outputs.test }}
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/deeptb:latest
    steps: 
      - name: Checkout
        id: s1
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Set repository ownership and permissions
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global --add safe.directory /github/home
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          chown -R github-actions:github-actions .
          chmod -R 755 .
      - name: Install DeePTB & Run Test
        id: s2
        run: |
         bash ut.sh
          
          
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          OUTPUT2: ${{needs.build.outputs.output2}}
          OUTPUT3: ${{needs.build.outputs.output3}}
        run: echo "$OUTPUT1 $OUTPUT2"
